include: package:very_good_analysis/analysis_options.5.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false

analyzer:
  exclude:
    - lib/src/core/localization/generated
    # - packages/
    - "**/*.g.dart"
    # - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"